import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[font]
size = 14.0

[font.normal]
family = "CodeNewRoman NF"

[window]
decorations = "none"
dynamic_padding = true

[mouse]
hide_when_typing = true