general.import = [
    "~/.config/alacritty/themes/dark.toml"
]

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Propo"

[window]
decorations = "none"
dynamic_padding = true

[mouse]
hide_when_typing = true 