# Screen configuration
SCREEN_PRIMARY="DVI-I-1-1"
SCREEN_PRIMARY_MODE="2560x1440"
SCREEN_PRIMARY_RATE="120.00"
SCREEN_LEFT="DVI-I-2-2"
SCREEN_LEFT_MODE="2560x1440"
SCREEN_LEFT_RATE="120.00"
SCREEN_BOTTOM="eDP-1"
SCREEN_BOTTOM_MODE="1920x1080"
SCREEN_BOTTOM_RATE="60.16"
