#! /bin/sh

chosen=$(printf "Power Off\nRestart" | rofi -dmenu -i -p "Power Menu")

case $chosen in
    "Power Off")
        systemctl poweroff
        ;;
    "Restart")
        systemctl reboot
        ;;
esac
